### ISSUE TITLE
Add support for Cloudflare managed Iceberg

### ISSUE THREAD

**Issue by emgeee** [duckdb/duckdb-iceberg#182]
Cloudflare just dropped an iceberg managed catalog for R2 and it would be great to be able to query it using duckdb: https://blog.cloudflare.com/r2-data-catalog-public-beta/

Currently, it seems that the iceberg s3 implementation relies on using to AWS ARNs to refer to the s3 bucket, which is not something R2 has an equivalent of.

Eventually, I imagine it'd make sense to be able to support any catalog using Iceberg RESTCatalog

**Comment by Tishj** [comment]
```py
catalog = RestCatalog(
    name="my_catalog",
    warehouse=WAREHOUSE,
    uri=CATALOG_URI,
    token=TOKEN,
)
```

This looks to me like it translates to:
```sql
attach '<WAREHOUSE>' as my_catalog (
    TYPE iceberg,
    ENDPOINT <CATALOG_URI>,
    TOKEN <TOKEN>
);
```

**Comment by Tishj** [comment]
We just released duckdb-iceberg for 1.2.2, that should include the changes of #142 which enables the above comment 👍 
Let me know if you run into any issues connecting to the Cloudflare managed Iceberg REST Catalog, I suspect this should just work now.

**Comment by emgeee** [comment]
Interesting, I've tried attaching the bucket above using duckdb 1.2.2 (using the ui). I can see the catalog, schema, and table on the left under "attached databases" however when I try to query some records using the code generated via the "query in current notebook" option I get the error: `Catalog Error: SET schema: No catalog + schema named "my_catalog.main" found.`

**Comment by Tishj** [comment]
Hmm try `USE my_catalog.<namespace>;`
I think by default we look in the `main` schema, but Iceberg REST Catalogs don't seem to use this same standard, so our defaults fail.

Your table lives under a "namespace", which gets turned into a schema in the catalog we attach.

**Comment by emgeee** [comment]
different error but still not working `Invalid Configuration Error: Invalid field found while parsing field: type`. I don't know enough about the inner workings of duckdb/iceberg to really 

For reference, I generated the sample table using a pyiceberg.catalog.rest.RestCatalog and am able to successfully query it using pyiceberg.

**Comment by Tishj** [comment]
See #171, fix for that is in the works :)

**Comment by tobilg** [comment]
@Tishj as https://github.com/duckdb/duckdb-iceberg/pull/207 is closed, should this now work?

**Comment by Tishj** [comment]
> [@Tishj](https://github.com/Tishj) as [#207](https://github.com/duckdb/duckdb-iceberg/pull/207) is closed, should this now work?

The "Invalid field found while parsing field: type" error was fixed by #207 
The R2 catalog support was added by #202

**Comment by tobilg** [comment]
> > [@Tishj](https://github.com/Tishj) as [#207](https://github.com/duckdb/duckdb-iceberg/pull/207) is closed, should this now work?
> 
> The "Invalid field found while parsing field: type" error was fixed by [#207](https://github.com/duckdb/duckdb-iceberg/pull/207) The R2 catalog support was added by [#202](https://github.com/duckdb/duckdb-iceberg/pull/202)

Thank you for the clarification! Sorry for the follow-up question, will this work with v1.2.1 as well, or only v1.2.2 upwards? Thanks again!

**Comment by Tishj** [comment]
The next release will be 1.3.0, these changes are not backported

**Comment by tobilg** [comment]
> The next release will be 1.3.0, these changes are not backported

So that means that the nightly extension builds will also not have it, correct?

**Comment by Tmonster** [comment]
@emgeee closing this now as fixed. Feel free to reopen if you are still experiencing issues
